<?php
// module/Album/view/album/album/index.phtml:

$title = 'Home';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr>

<div class="col-md-8">

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="<?php echo $this->basePath() . '/img/one.jpg' ?>" class="img-responsive" height="250">
            </div>
            <div class="item">
                <img src="<?php echo $this->basePath() . '/img/two.jpg' ?>" height="250"></div>
            <div class="item">
                <img src="<?php echo $this->basePath() . '/img/three.jpg' ?> "class="img-responsive" height="250"></div>

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>


    <h1 class="text-center">One Stop Shop<br>
        <small>On Your Way Home | ගෙදර යන ගමන් |வீடு செல்லும் போது</small>
    </h1>


</div>
